ec-stats: ec.stats.test.StatisticsTest Class Reference
ec.stats.test.StatisticsTest Class Reference
Public Member Functions
void beforeEachTest ()
void testCount ()
void testMin ()
void testMax ()
void testMean ()
void testStds ()
void testAddDataAddMinNumber ()
void testAddDataAddMaxNumber ()
void testAddDataNewMean ()
void testAddDataNewStd ()
void testStats ()
void testStatsNewDataMin ()
void testStatsNewDataMax ()
void testStatsNewDataMean ()
void testStatsNewDataStd ()
Static Public Member Functions
static void init ()
Static Private Attributes
static ECStatistics ecstats
static double [] inputData
static int expectedInputCount
static double expectedInputMin
static double expectedInputMax
static double expectedInputMean
static double expectedInputStd
Detailed Description
Definition at line 13 of file StatisticsTest.java.
Member Function Documentation
beforeEachTest()
void ec.stats.test.StatisticsTest.beforeEachTest ()
Definition at line 40 of file StatisticsTest.java.
References ec.stats.test.StatisticsTest.init().
init()
static void ec.stats.test.StatisticsTest.init () static
Definition at line 24 of file StatisticsTest.java.
References ec.stats.ECStatistics.addData(), and ec.stats.test.StatisticsTest.expectedInputCount.
Referenced by ec.stats.test.StatisticsTest.beforeEachTest().
testAddDataAddMaxNumber()
void ec.stats.test.StatisticsTest.testAddDataAddMaxNumber ()
Definition at line 84 of file StatisticsTest.java.
References ec.stats.ECStatistics.addData(), ec.stats.ECStatistics.getCount(), and ec.stats.ECStatistics.getMax().
testAddDataAddMinNumber()
void ec.stats.test.StatisticsTest.testAddDataAddMinNumber ()
Definition at line 70 of file StatisticsTest.java.
References ec.stats.ECStatistics.addData(), ec.stats.ECStatistics.getCount(), and ec.stats.ECStatistics.getMin().
testAddDataNewMean()
void ec.stats.test.StatisticsTest.testAddDataNewMean ()
Definition at line 98 of file StatisticsTest.java.
References ec.stats.ECStatistics.addData(), ec.stats.ECStatistics.getCount(), and ec.stats.ECStatistics.getMean().
testAddDataNewStd()
void ec.stats.test.StatisticsTest.testAddDataNewStd ()
Definition at line 113 of file StatisticsTest.java.
References ec.stats.ECStatistics.addData(), ec.stats.ECStatistics.getCount(), and ec.stats.ECStatistics.getSTD().
testCount()
void ec.stats.test.StatisticsTest.testCount ()
Definition at line 45 of file StatisticsTest.java.
References ec.stats.ECStatistics.getCount().
testMax()
void ec.stats.test.StatisticsTest.testMax ()
Definition at line 55 of file StatisticsTest.java.
References ec.stats.ECStatistics.getMax().
testMean()
void ec.stats.test.StatisticsTest.testMean ()
Definition at line 60 of file StatisticsTest.java.
References ec.stats.ECStatistics.getMean().
testMin()
void ec.stats.test.StatisticsTest.testMin ()
Definition at line 50 of file StatisticsTest.java.
References ec.stats.ECStatistics.getMin().
testStats()
void ec.stats.test.StatisticsTest.testStats ()
Definition at line 128 of file StatisticsTest.java.
References ec.stats.ECStatistics.getCount(), ec.stats.ECStatistics.getMax(), ec.stats.ECStatistics.getMean(), ec.stats.ECStatistics.getMin(), ec.stats.ECStatistics.getSTD(), and ec.stats.ECStatistics.stats().
testStatsNewDataMax()
void ec.stats.test.StatisticsTest.testStatsNewDataMax ()
Definition at line 151 of file StatisticsTest.java.
References ec.stats.ECStatistics.addData(), ec.stats.ECStatistics.getCount(), ec.stats.ECStatistics.getMax(), and ec.stats.ECStatistics.stats().
testStatsNewDataMean()
void ec.stats.test.StatisticsTest.testStatsNewDataMean ()
Definition at line 163 of file StatisticsTest.java.
References ec.stats.ECStatistics.addData(), ec.stats.ECStatistics.getCount(), ec.stats.ECStatistics.getMean(), and ec.stats.ECStatistics.stats().
testStatsNewDataMin()
void ec.stats.test.StatisticsTest.testStatsNewDataMin ()
Definition at line 139 of file StatisticsTest.java.
References ec.stats.ECStatistics.addData(), ec.stats.ECStatistics.getCount(), ec.stats.ECStatistics.getMin(), and ec.stats.ECStatistics.stats().
testStatsNewDataStd()
void ec.stats.test.StatisticsTest.testStatsNewDataStd ()
Definition at line 176 of file StatisticsTest.java.
References ec.stats.ECStatistics.addData(), ec.stats.ECStatistics.getCount(), ec.stats.ECStatistics.getSTD(), and ec.stats.ECStatistics.stats().
testStds()
void ec.stats.test.StatisticsTest.testStds ()
Definition at line 65 of file StatisticsTest.java.
References ec.stats.ECStatistics.getSTD().
Member Data Documentation
ecstats
ECStatistics ec.stats.test.StatisticsTest.ecstats static private
Definition at line 14 of file StatisticsTest.java.
expectedInputCount
int ec.stats.test.StatisticsTest.expectedInputCount static private
Definition at line 17 of file StatisticsTest.java.
Referenced by ec.stats.test.StatisticsTest.init().
expectedInputMax
double ec.stats.test.StatisticsTest.expectedInputMax static private
Definition at line 19 of file StatisticsTest.java.
expectedInputMean
double ec.stats.test.StatisticsTest.expectedInputMean static private
Definition at line 20 of file StatisticsTest.java.
expectedInputMin
double ec.stats.test.StatisticsTest.expectedInputMin static private
Definition at line 18 of file StatisticsTest.java.
expectedInputStd
double ec.stats.test.StatisticsTest.expectedInputStd static private
Definition at line 21 of file StatisticsTest.java.
inputData
double [] ec.stats.test.StatisticsTest.inputData static private
Definition at line 16 of file StatisticsTest.java.
The documentation for this class was generated from the following file:
src/ec/stats/test/StatisticsTest.java