ec-stats: ec.stats.MyStatistics Class Reference
ec.stats.MyStatistics Class Reference
MyStatistics class for the main function.
Static Public Member Functions
static void main (String[] args)
Detailed Description
MyStatistics class for the main function.
main function creates ECStatistics instance
Add data 1..10000 with method addData()
Print the result of count/min/max/mean/standard deviation
Definition at line 30 of file MyStatistics.java.
Member Function Documentation
main()
static void ec.stats.MyStatistics.main (String [] args) static
Definition at line 31 of file MyStatistics.java.
References ec.stats.ECStatistics.addData(), ec.stats.ECStatistics.getCount(), ec.stats.ECStatistics.getMax(), ec.stats.ECStatistics.getMean(), ec.stats.ECStatistics.getMin(), and ec.stats.ECStatistics.getSTD().
The documentation for this class was generated from the following file:
src/ec/stats/MyStatistics.java