ec-stats: ec.stats.ECStatistics Class Reference
ec.stats.ECStatistics Class Reference
This class implements the Statistics interface and methods to calculate statistics on input data.
Public Member Functions
ECStatistics ()
Compute and return the difference of two operands.
void stats ()
Compute the count/min/max/mean/standard deviation.
void addData (double d)
Add double to the data array and re-compute the count/min/max/mean/standard deviation.
int getCount ()
Getter for the count property.
double getMin ()
Getter for the min property.
double getMax ()
Getter for the max property.
double getMean ()
Getter for the mean property.
double getSTD ()
Getter for the std property.
Public Member Functions inherited from ec.stats.Statistics
void stats ()
void addData (double d)
int getCount ()
double getMin ()
double getMax ()
double getMean ()
double getSTD ()
Private Member Functions
double computeTotalSTD ()
Compute the total standard deviation for all values in the data array.
Private Attributes
int count
double min
double max
double mean
double std
double totalSum
Detailed Description
This class implements the Statistics interface and methods to calculate statistics on input data.
Definition at line 10 of file ECStatistics.java.
Constructor & Destructor Documentation
ECStatistics()
ec.stats.ECStatistics.ECStatistics ()
Compute and return the difference of two operands.
Definition at line 24 of file ECStatistics.java.
Member Function Documentation
addData()
void ec.stats.ECStatistics.addData (double d)
Add double to the data array and re-compute the count/min/max/mean/standard deviation.
Parameters
d
Definition at line 62 of file ECStatistics.java.
References ec.stats.ECStatistics.computeTotalSTD(), ec.stats.ECStatistics.count, ec.stats.ECStatistics.max, and ec.stats.ECStatistics.min.
Referenced by ec.stats.test.StatisticsTest.init(), ec.stats.MyStatistics.main(), ec.stats.test.StatisticsTest.testAddDataAddMaxNumber(), ec.stats.test.StatisticsTest.testAddDataAddMinNumber(), ec.stats.test.StatisticsTest.testAddDataNewMean(), ec.stats.test.StatisticsTest.testAddDataNewStd(), ec.stats.test.StatisticsTest.testStatsNewDataMax(), ec.stats.test.StatisticsTest.testStatsNewDataMean(), ec.stats.test.StatisticsTest.testStatsNewDataMin(), and ec.stats.test.StatisticsTest.testStatsNewDataStd().
computeTotalSTD()
double ec.stats.ECStatistics.computeTotalSTD () private
Compute the total standard deviation for all values in the data array.
Returns
totalStd
Definition at line 137 of file ECStatistics.java.
Referenced by ec.stats.ECStatistics.addData(), and ec.stats.ECStatistics.stats().
getCount()
int ec.stats.ECStatistics.getCount ()
Getter for the count property.
Returns
count
Definition at line 83 of file ECStatistics.java.
References ec.stats.ECStatistics.count.
Referenced by ec.stats.MyStatistics.main(), ec.stats.test.StatisticsTest.testAddDataAddMaxNumber(), ec.stats.test.StatisticsTest.testAddDataAddMinNumber(), ec.stats.test.StatisticsTest.testAddDataNewMean(), ec.stats.test.StatisticsTest.testAddDataNewStd(), ec.stats.test.StatisticsTest.testCount(), ec.stats.test.StatisticsTest.testStats(), ec.stats.test.StatisticsTest.testStatsNewDataMax(), ec.stats.test.StatisticsTest.testStatsNewDataMean(), ec.stats.test.StatisticsTest.testStatsNewDataMin(), and ec.stats.test.StatisticsTest.testStatsNewDataStd().
getMax()
double ec.stats.ECStatistics.getMax ()
Getter for the max property.
Returns
max
Definition at line 105 of file ECStatistics.java.
References ec.stats.ECStatistics.max.
Referenced by ec.stats.MyStatistics.main(), ec.stats.test.StatisticsTest.testAddDataAddMaxNumber(), ec.stats.test.StatisticsTest.testMax(), ec.stats.test.StatisticsTest.testStats(), and ec.stats.test.StatisticsTest.testStatsNewDataMax().
getMean()
double ec.stats.ECStatistics.getMean ()
Getter for the mean property.
Returns
mean
Definition at line 116 of file ECStatistics.java.
References ec.stats.ECStatistics.mean.
Referenced by ec.stats.MyStatistics.main(), ec.stats.test.StatisticsTest.testAddDataNewMean(), ec.stats.test.StatisticsTest.testMean(), ec.stats.test.StatisticsTest.testStats(), and ec.stats.test.StatisticsTest.testStatsNewDataMean().
getMin()
double ec.stats.ECStatistics.getMin ()
Getter for the min property.
Returns
min
Definition at line 94 of file ECStatistics.java.
References ec.stats.ECStatistics.min.
Referenced by ec.stats.MyStatistics.main(), ec.stats.test.StatisticsTest.testAddDataAddMinNumber(), ec.stats.test.StatisticsTest.testMin(), ec.stats.test.StatisticsTest.testStats(), and ec.stats.test.StatisticsTest.testStatsNewDataMin().
getSTD()
double ec.stats.ECStatistics.getSTD ()
Getter for the std property.
Returns
std
Definition at line 127 of file ECStatistics.java.
References ec.stats.ECStatistics.std.
Referenced by ec.stats.MyStatistics.main(), ec.stats.test.StatisticsTest.testAddDataNewStd(), ec.stats.test.StatisticsTest.testStats(), ec.stats.test.StatisticsTest.testStatsNewDataStd(), and ec.stats.test.StatisticsTest.testStds().
stats()
void ec.stats.ECStatistics.stats ()
Compute the count/min/max/mean/standard deviation.
Definition at line 37 of file ECStatistics.java.
References ec.stats.ECStatistics.computeTotalSTD(), ec.stats.ECStatistics.count, ec.stats.ECStatistics.max, and ec.stats.ECStatistics.min.
Referenced by ec.stats.test.StatisticsTest.testStats(), ec.stats.test.StatisticsTest.testStatsNewDataMax(), ec.stats.test.StatisticsTest.testStatsNewDataMean(), ec.stats.test.StatisticsTest.testStatsNewDataMin(), and ec.stats.test.StatisticsTest.testStatsNewDataStd().
Member Data Documentation
count
int ec.stats.ECStatistics.count private
Definition at line 13 of file ECStatistics.java.
Referenced by ec.stats.ECStatistics.addData(), ec.stats.ECStatistics.getCount(), and ec.stats.ECStatistics.stats().
max
double ec.stats.ECStatistics.max private
Definition at line 15 of file ECStatistics.java.
Referenced by ec.stats.ECStatistics.addData(), ec.stats.ECStatistics.getMax(), and ec.stats.ECStatistics.stats().
mean
double ec.stats.ECStatistics.mean private
Definition at line 16 of file ECStatistics.java.
Referenced by ec.stats.ECStatistics.getMean().
min
double ec.stats.ECStatistics.min private
Definition at line 14 of file ECStatistics.java.
Referenced by ec.stats.ECStatistics.addData(), ec.stats.ECStatistics.getMin(), and ec.stats.ECStatistics.stats().
std
double ec.stats.ECStatistics.std private
Definition at line 17 of file ECStatistics.java.
Referenced by ec.stats.ECStatistics.getSTD().
totalSum
double ec.stats.ECStatistics.totalSum private
Definition at line 19 of file ECStatistics.java.
The documentation for this class was generated from the following file:
src/ec/stats/ECStatistics.java