
package ec.lab.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.3.3
 * Thu Oct 28 12:53:06 EDT 2021
 * Generated source version: 3.3.3
 */

@XmlRootElement(name = "predictResponse", namespace = "http://lab.ec/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "predictResponse", namespace = "http://lab.ec/")

public class PredictResponse {

    @XmlElement(name = "return")
    private java.lang.String _return;

    public java.lang.String getReturn() {
        return this._return;
    }

    public void setReturn(java.lang.String new_return)  {
        this._return = new_return;
    }

}

