
package ec.lab.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.3.3
 * Thu Oct 28 12:53:06 EDT 2021
 * Generated source version: 3.3.3
 */

@XmlRootElement(name = "predict", namespace = "http://lab.ec/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "predict", namespace = "http://lab.ec/")

public class Predict {

    @XmlElement(name = "arg0")
    private java.lang.String arg0;

    public java.lang.String getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.String newArg0)  {
        this.arg0 = newArg0;
    }

}

