
package stats.ejb.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.3.3
 * Fri Oct 29 16:09:21 EDT 2021
 * Generated source version: 3.3.3
 */

@XmlRootElement(name = "getCountResponse", namespace = "http://ejb.stats/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getCountResponse", namespace = "http://ejb.stats/")

public class GetCountResponse {

    @XmlElement(name = "return")
    private int _return;

    public int getReturn() {
        return this._return;
    }

    public void setReturn(int new_return)  {
        this._return = new_return;
    }

}

