
package stats.ejb.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.3.3
 * Fri Oct 29 16:09:21 EDT 2021
 * Generated source version: 3.3.3
 */

@XmlRootElement(name = "getMean", namespace = "http://ejb.stats/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getMean", namespace = "http://ejb.stats/")

public class GetMean {


}

