My Doxygen: ec.lab.CalTest2 Class Reference
ec.lab.CalTest2 Class Reference
Public Member Functions
void testSum ()
void testDivison ()
void testDivisionException () throws Exception
Static Public Member Functions
static void initCalculator ()
Static Private Attributes
static Calculator calculator
Detailed Description
Definition at line 11 of file CalTest2.java.
Member Function Documentation
initCalculator()
static void ec.lab.CalTest2.initCalculator () static
Definition at line 15 of file CalTest2.java.
testDivisionException()
void ec.lab.CalTest2.testDivisionException () throws Exception
Definition at line 38 of file CalTest2.java.
References ec.lab.Calculator.divison().
testDivison()
void ec.lab.CalTest2.testDivison ()
Definition at line 28 of file CalTest2.java.
References ec.lab.Calculator.divison().
testSum()
void ec.lab.CalTest2.testSum ()
Definition at line 21 of file CalTest2.java.
References ec.lab.Calculator.sum().
Member Data Documentation
calculator
Calculator ec.lab.CalTest2.calculator static private
Definition at line 12 of file CalTest2.java.
The documentation for this class was generated from the following file:
test/ec/lab/CalTest2.java