My Doxygen: ec.lab.CalTest Class Reference
ec.lab.CalTest Class Reference
Public Member Functions
void beforeEachTest ()
void afterEachTest ()
void testSum ()
void testDivison ()
void testDivisionException () throws Exception
void testEqual ()
Static Public Member Functions
static void initCalculator ()
Static Private Attributes
static Calculator calculator
Detailed Description
Definition at line 13 of file CalTest.java.
Member Function Documentation
afterEachTest()
void ec.lab.CalTest.afterEachTest ()
Definition at line 28 of file CalTest.java.
beforeEachTest()
void ec.lab.CalTest.beforeEachTest ()
Definition at line 23 of file CalTest.java.
initCalculator()
static void ec.lab.CalTest.initCalculator () static
Definition at line 18 of file CalTest.java.
testDivisionException()
void ec.lab.CalTest.testDivisionException () throws Exception
Definition at line 49 of file CalTest.java.
References ec.lab.Calculator.divison().
testDivison()
void ec.lab.CalTest.testDivison ()
Definition at line 39 of file CalTest.java.
References ec.lab.Calculator.divison().
testEqual()
void ec.lab.CalTest.testEqual ()
Definition at line 55 of file CalTest.java.
References ec.lab.CalTest.calculator, and ec.lab.Calculator.equalIntegers().
testSum()
void ec.lab.CalTest.testSum ()
Definition at line 33 of file CalTest.java.
References ec.lab.Calculator.sum().
Member Data Documentation
calculator
Calculator ec.lab.CalTest.calculator static private
Definition at line 15 of file CalTest.java.
Referenced by ec.lab.CalTest.testEqual().
The documentation for this class was generated from the following file:
test/ec/lab/CalTest.java